
# Корневой блок, где мы описываем все контейнеры,
# которые должны работать в единой сети.
services:   
  
# Имя нашего сервиса (и по совместительству доменное имя
# внутри сети Docker)
  app:   

#.Указывает Docker Compose собрать образ из контекста текущей
# папки (.), используя рецепт из Dockerfile.app        
    build:
      context: .         # Где искать файлы (текущая папка)
      dockerfile: Dockerfile.app  # Какой рецепт использовать для сборки API
    ports:
      - "8000:8000"      # Проброс порта (Компьютер:Контейнер), чтобы API был доступен на localhost:8000


#Автоматическая проверка работоспособности сервиса:
    healthcheck:         # Проверка: «Сервер уже поднялся и готов принимать запросы?»
      
      # выполняет запрос curl -f внутри контейнера app. 
      #Если эндпоинт отвечает ошибкой (4xx/5xx) или не отвечает 
      #вовсе, команда возвращает exit 1 (провал).
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]  # Каждые 5 сек (interval) делает запрос на http://localhost:8000/health
      
      #делать проверку каждые 3 секунды.
      interval: 5s 

      #если ответ не пришел за 2 секунды, считать попытку неудачной.
      timeout: 3s 

      #сделать 5 попыток перед тем, как окончательно 
      #присвоить контейнеру статус unhealthy
      retries: 5         # Если 5 раз ответил OK — статус меняется на "healthy"


# Вторая служба, содержащая фреймворк с автотестами Pytest.
  test-runner:           
    build:
      context: .
      dockerfile: Dockerfile.tests # Какой рецепт использовать для тестов
    depends_on:
      app:
        condition: service_healthy # ГЛАВНАЯ МАГИЯ: ждем, пока 'app' не станет "healthy"
    volumes:
      - ./allure-results:/workspace/allure-results # Сохраняем отчеты из контейнера на ваш диск