# Syntax of the Docker specification.
version: '3.8'

services:
  
  # Service name in the initial Docker network. 
  # This name is used for callind containers to the database 
  db:
    
    # Using the light PostgreSQL iso on the Alpine Linux base
    image: postgres:15-alpine
    container_name: postgres_db

    # Name of the variables, that iso Postgess reads while 
    # first start for automatic creation user, password and database
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: patients_db
    ports:
      - "5432:5432"
    healthcheck:
    
    # uses the tool pg_isready, witch checks if the base 
    # is ready to accept the requests from user
      test: ["CMD-SHELL", "pg_isready -U user -d patients_db"]
      interval: 3s
      timeout: 3s
      
      # if 5 checks were failed - the container gives
      # unhealthy status
      retries: 5
    networks:
      - app-network   
  
# Service name
  app:   

# Explain, that Docker Compose need to build from the current 
# folder (.), by using the recipe from the Dockerfile.app        
    build:
      context: .
      dockerfile: Dockerfile.app  
    
    # Port open locally to FastAPI by http://localhost:8000
    ports:
      - "8000:8000"
    environment:
    
    # Reports the connection string to database
    # (instead of localhost we use the db name)
      - DATABASE_URL=postgresql://user:password@db:5432/patients_db
    depends_on:
      db:

      # tells Docker Compose not to start the application until
      # the `db` service passes its health check and becomes healthy.
        condition: service_healthy
    
    healthcheck:

    # checks the readiness of the web server itself via an 
    # HTTP GET request to the /health endpoint
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - app-network

  test-runner:           
    build:
      context: .
      dockerfile: Dockerfile.tests
    container_name: test_runner
    depends_on:
      app:
      
      # tells Docker Compose not to start the application until
      # the `db` service passes its health check and becomes healthy.
        condition: service_healthy
    
    # mounts a folder from the container to your local disk
    # so that the Allure result files are preserved after the container stops.
    volumes:
      - ./allure-results:/app/allure-results
    networks:
      - app-network

# defines an isolated bridge-type virtual network. 
# All three containers (db, app, test-runner) are located in this network
# can see each other by service name via Docker's internal DNS.
networks:
  app-network:
    driver: bridge