# 1. Берем тот же базовый образ Python
FROM python:3.11-slim

# 2. Создаем рабочую папку
WORKDIR /workspace

# 3. Копируем зависимости и устанавливаем их
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# 4. Копируем тесты и всю структуру проекта
COPY . .

# 5. Команда запуска автотестов Pytest с генерацией отчетов Allure
CMD ["pytest", "--alluredir=allure-results"]